blog/urls.py
# blog/urls.py

# Django modules
from django.conf.urls import url
from django.urls import path

from blog.views import PostListView, PostDetailView

app_name = 'blog'

urlpatterns = [
    # url(r'^$', greeting),
    path('', PostListView, name='postlist'),
    path('<int:year>/<int:month>/<int:day>/<str:slug>/', PostDetailView, name='postdetail'),
]

organizer/urls.py
# organizer/urls.py

# Django modules
from django.conf.urls import url
from django.urls import path

from organizer.views import (
    StartupListView, StartupDetailView,
    TagListView, TagDetailView)

app_name = 'organizer'

urlpatterns = [
    path('startups/', StartupListView, name='startuplist'),
    path('startup/<str:slug>/', StartupDetailView, name='startupdetail'),
    path('tags/', TagListView, name='taglist'),
    path('tag/<str:slug>/', TagDetailView, name='tagdetail'),
]

suorganizer/urls.py
# suorganizer/urls.py

# Django modules
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('organizer.urls', namespace='organizer')),
]

blog/models.py
# blog/models.py

# Django modules
from django.db import models
from django.urls import reverse

# Locals
from organizer.models import Startup, Tag

# Create your models here.

class Post(models.Model):
    title 		= models.CharField(max_length=63)
    slug 		= models.SlugField(max_length=63,help_text='A label for URL config',unique_for_month='pub_date')
    text 		= models.TextField()
    pub_date 	= models.DateField('date published',auto_now_add=True)
    tags 		= models.ManyToManyField(Tag, related_name='blog_posts')
    startups 	= models.ManyToManyField(Startup, related_name='blog_posts')

    class Meta:
        verbose_name 	= 'blog post'
        ordering 		= ['-pub_date', 'title']
        get_latest_by 	= 'pub_date'

    def __str__(self):
        return "{} on {}".format(
            self.title,
            self.pub_date.strftime('%Y-%m-%d'))

    def get_post_absolute_url(self):
        return reverse('blog:postdetail',
                        args=[
                            self.pub_date.year,
                            self.pub_date.month,
                            self.pub_date.day,
                            self.slug
                        ])

organizer/models.py
# organizer/models.py

# Django modules
from django.db import models
from django.urls import reverse

# Locals

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31,unique=True,help_text='A label for URL config.')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_tag_absolute_url(self):
        return reverse('organizer:tagdetail', 
                        kwargs={'slug':self.slug})



class Startup(models.Model):
    name 			= models.CharField(max_length=31, db_index=True)
    slug 			= models.SlugField(max_length=31,unique=True,help_text='A label for URL config.')
    description 	= models.TextField()
    founded_date 	= models.DateField('date founded')
    contact 		= models.EmailField()
    website 		= models.URLField(max_length=255)
    tags 			= models.ManyToManyField(Tag)

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

    def __str__(self):
        return self.name

    def get_startup_absolute_url(self):
        return reverse('organizer:startupdetail', 
                        kwargs={'slug':self.slug})

class NewsLink(models.Model):
    title 		= models.CharField(max_length=63)
    pub_date 	= models.DateField('date published')
    link 		= models.URLField(max_length=255)
    startup 	= models.ForeignKey(Startup, on_delete=models.CASCADE)

    class Meta:
        verbose_name 	= 'news article'
        ordering 		= ['-pub_date']
        get_latest_by 	= 'pub_date'

    def __str__(self):
        return "{}: {}".format(
            self.startup, self.title)

blog/views.py
# blog/views/py

# Django modules
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

# Locals
from blog.models import Post

# Create your views here.

def PostListView(request):
    post_list = Post.objects.all()
    context = {
        'post_list':post_list
    }
    return render(request, 'blog/post_list.html', context)
    

def PostDetailView(request, year, month, day, slug):
    post = get_object_or_404(
            Post,
            pub_date__year=year,
            pub_date__month=month,
            pub_date__day=day,
            slug=slug)
    context = {
        'post':post
    }
    return render(request, 'blog/post_detail.html', context)

organizer/views.py
# organizer/views.py

# Django modules
from django.shortcuts import render
from django.http.response import HttpResponse, Http404
from django.shortcuts import get_object_or_404

# Locals
from organizer.models import Startup, Tag

# Create your views here.


def StartupListView(request):
    startup_list = Startup.objects.all()
    context = {
        'startup_list': startup_list
    } 
    return render(request, 'organizer/startup_list.html', context)


def StartupDetailView(request, slug):
    startup = get_object_or_404(Startup, slug__iexact=slug)

    context = {
        'startup': startup
    } 
    return render(request, 'organizer/startup_detail.html', context)


def TagListView(request):
    tag_list = Tag.objects.all()
    context = {
        'tag_list': tag_list
    }
    return render(request, 'organizer/tag_list.html', context)


def TagDetailView(request, slug):
    try:
        tag = Tag.objects.get(slug__iexact=slug)
        # tag = get_object_or_404(Tag, slug__iexact=slug)
    except Tag.DoesNotExist:
        return HttpResponse('<h1>Tag not found!</h1>')
    context = {
        'tag': tag
    }
    return render(request, 'organizer/tag_detail.html', context)

blog/templates/blog/base_blog.html
{% extends parent_template|default:"base.html" %}

blog/templates/blog/post_detail.html
<article>

    <header>
      <h2>{{ post.title|title }}</h2>
      <p>
        Written on
        <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
          {{ post.pub_date|date:"l, F j, Y" }}
        </time>
      </p>
    </header>

    {{ post.text|linebreaks }}

  {% if post.startups.all or post.tags.all %}
    <footer>

      {% if post.startups.all %}
          <section>
            <h3>Startup{{ post.startups.count|pluralize }}</h3>
            <ul>
              {% for startup in post.startups.all %}
                <li><a href="{{ startup.get_startup_absolute_url }}">
                  {{ startup.name }}
                </a></li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

      {% if post.tags.all %}
          <section>
            <h3>Tag{{ post.tags.count|pluralize }}</h3>
            <ul>
              {% for tag in post.tags.all %}
                <li><a href="{{ tag.get_tag_absolute_url }}">
                  {{ tag.name|title }}
                </a></li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

    </footer>
  {% endif %}

</article>

blog/templates/blog/post_list.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
{{ block.super }} - Blog
{% endblock %}

{% block content %}
      {% for post in post_list %}
        <article>
          <header>
            <h2>
              <a href="{% url 'blog:postdetail' post.pub_date.year post.pub_date.month post.pub_date.day post.slug %}">

                {{ post.title|title }}</a>
            </h2>
            <p>
              Written on:
              <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
                {{ post.pub_date|date:"l, F j, Y" }}
              </time>
            </p>
          </header>
          <p>{{ post.text|truncatewords:20 }}</p>
          <p>
            <a href="{{ post.get_post_absolute_url }}">
              Read more&hellip;</a>
          </p>
        </article>
      {% empty %}
        <p><em>No Blog Posts Available</em></p>
      {% endfor %}
{% endblock %}

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

organizer/templates/organizer/startup_detail.html
<article>

  <h2>{{ startup.name }}</h2>
  <dl>
    <dt>Date Founded</dt>
      <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
    <dt>Website</dt>
      <dd>{{ startup.website|urlize }}</dd>
    <dt>Contact</dt>
      <dd>{{ startup.contact }}</dd>

      <dt>Tag{{ startup.tags.count|pluralize }}</dt>
        {% for tag in startup.tags.all %}
          <dd><a href="">
            {{ tag.name|title }}
          </a></dd>
        {% endfor %}

  </dl>

  {{ startup.description|linebreaks }}

      {% if startup.newslink_set.all %}
          <section>
            <h3>Recent News</h3>
            <ul>
              {% for newslink in startup.newslink_set.all %}
                <li>
                  <a href="{{ newslink.link }}">
                    {{ newslink.title|title }}</a>
                </li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

      {% if startup.blog_posts.all %}
          <section>
            <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
            <ul>
              {% for post in startup.blog_posts.all %}
                <li>
                  <a href="{{ post.get_post_absolute_url }}">
                    {{ post.title|title }}</a>
                </li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

</article>

organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startups
{% endblock %}

{% block content %}
  <h2>Startup List</h2>
  <ul>
    {% for startup in startup_list %}
      <li>
        <a href="{{ startup.get_startup_absolute_url }}">
          {{ startup.name }}</a>
      </li>
    {% empty %}
      <li><em>No Startups Available</em></li>
    {% endfor %}
  </ul>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block content %}
  <h2>{{ tag.name|title }}</h2>
  {% if tag.startup_set.all %}
    <section>
      <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
      <p>
        Tag is associated with
        {{ tag.startup_set.count }}
        startup{{ tag.startup_set.count|pluralize }}.
      </p>
      <ul>
        {% for startup in tag.startup_set.all %}
          <li><a href="{{ startup.get_startup_absolute_url }}">
            {{ startup.name }}
          </a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
      {% if tag.blog_posts.all %}
        <section>
          <h3>Blog Post{{ tag.blog_posts.count|pluralize }}</h3>
          <ul>
            {% for post in tag.blog_posts.all %}
              <li><a href="">
                {{ post.title|title }}
              </a></li>
            {% endfor %}
          </ul>
        </section>
      {% endif %}
      {% if not tag.startup_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content.</p>
      {% endif %}
{% endblock %}

organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Tag List
{% endblock %}

{% block content %}
  <h2>Tag List</h2>
  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="{{ tag.get_tag_absolute_url }}">
          {{ tag.name|title }}</a>
      </li>
    {% empty %}
      <li><em>There are currently no Tags available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
        Startup Organizer
      {% endblock %}
    </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if IE]><script
      src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
    </script><![endif]-->
  </head>

  <body>

    <div><!-- container -->
      <header>
          <h1>Startup Organizer</h1>
      </header>
      <nav>
        <ul>
          <li>
            <a href="{% url 'blog:postlist' %}">
              Blog</a></li>
          <li>
            <a href="{% url 'organizer:startuplist' %}">
              Startups</a></li>
          <li>
            <a href="{% url 'organizer:taglist' %}">
              Tags</a></li>
        </ul>
      </nav>
      <main>
        {% block content %}
          This is default content!
        {% endblock %}
      </main>
    </div><!-- container -->

    <footer>
      <p>
        &copy; 2015
        <a href="https://AndrewsForge.com/">
          Andrew Pinkham</a>
      </p>
      <p>
        Created for
        <a href="https://Django-Unleashed.com/">
          Django Unleashed</a>
      </p>
    </footer>

  </body>

</html>